import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Nav from '@/components/Nav';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
      >
        <Nav />
        <main className='flex flex-col items-center p-4 h-full overflow-y-scroll'>
          {children}
        </main>
        <footer className='flex justify-center  border-t-2 w-full '>
          hanaro 4
        </footer>
      </body>
    </html>
  );
}
